#!/bin/sh

MENU="900 1500"
SPELL="850 1700"
WHISTLE="700 1650"
FIGHT="600 1700"
CONFIRM=$FIGHT

tap() {
	adb shell input swipe $1 $2 $1 $2 100
	sleep 0.3
}

whistle() {
	tap $MENU
	tap $SPELL
	tap $WHISTLE
	tap $CONFIRM
}

fight() {
	for i in `seq 10`; do
		tap $CONFIRM
		tap $CONFIRM
		tap $CONFIRM
		tap $CONFIRM
		sleep 2
	done
}

while true; do
	echo -n "whistle/"
	whistle
	sleep 2

	echo "fight"
	fight
	sleep 2
done
