#!/bin/sh

MENU="900 1500"
SPELL="850 1700"
WHISTLE="700 1150"
FIGHT="600 1700"
ATTACK="300 1700"
CONFIRM=$ATTACK

tap() {
	adb shell input swipe $1 $2 $1 $2 100
	sleep 0.3
}

whistle() {
	tap $MENU
	tap $SPELL
	tap $WHISTLE
	tap $CONFIRM
}

fight() {
	tap $CONFIRM
	tap $CONFIRM
	tap $CONFIRM
	sleep 2
	tap $FIGHT
	tap $ATTACK
	tap $ATTACK
	sleep 15
}

end_fight() {
	tap $CONFIRM
	tap $CONFIRM
	tap $CONFIRM
	tap $CONFIRM
	tap $CONFIRM
	tap $CONFIRM
}

while true; do
	echo -n "whistle/"
	whistle
	sleep 2

	echo -n "fight/"
	fight
	echo -n "fight/"
	fight

	echo "end"
	end_fight
	sleep 2
done
