#!/bin/sh

MENU="950 1550"
SPELL="850 1700"
WHISTLE="700 1650"
FIGHT="650 1750"
CONFIRM=$FIGHT

tap() {
	adb shell input swipe $1 $2 $1 $2 100
	sleep 0.3
}

whistle() {
	tap $MENU
	tap $SPELL
	tap $WHISTLE
	tap $CONFIRM
	sleep 2
}

fight() {
	for i in `seq 8`; do
		tap $FIGHT
		tap $FIGHT
		tap $FIGHT
		tap $FIGHT
		sleep 2
	done
}

round=1
while true; do
	echo -n "round $round: "
	date +%H:%M:%S

	whistle
	fight

	round=$((round + 1))
done
