#!/bin/sh

MENU="100 1350"
SPELL="950 1450"
WHISTLE="550 1550"
USE="700 1400"
FIGHT="400 1550"
CONFIRM=$FIGHT

tap() {
	adb shell input swipe $1 $2 $1 $2 100
	sleep 0.3
}

whistle() {
	tap $MENU
	tap $SPELL
	tap $WHISTLE
	tap $USE
	tap $CONFIRM
	sleep 5
}

fight() {
	for i in `seq 10`; do
		tap $FIGHT
		tap $FIGHT
		tap $FIGHT
		tap $FIGHT
		sleep 2
	done
}

round=1
while true; do
	echo -n "round $round: "
	date +%H:%M:%S

	whistle
	fight

	round=$((round + 1))
done
